version: '3.7'

services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
  bot:
    build: .
    container_name: bot
    command: python bot.py
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - redis